### ISSUE TITLE
Issue when trying to add new training data to classifier

### ISSUE THREAD

**Issue by ericsavoiewaltz** [testdotai/classifier-builder#2] opened 2018-11-06 18:23 UTC
After training the classifier on some "paper airplane" images I followed the steps to bring the training data over to the `/usr/local/lib/node_modules/appium/node_modules/test-ai-classifier ` folder. 

After following the steps in the doc I got this error: `Encountered internal error running command: Error: Prediction result array had 107 elements but labels list had 106 elements. They need to match.`

I tried updating the labels.js files with my new "paper airplane" tag but that didn't change either value in the error message. 

Okay more information - I tried first replacing the contents of `/usr/local/lib/node_modules/appium/node_modules/test-ai-classifier/model/` with the contents of the generated `web_model` folder that is what happened to get this error: 

`Encountered internal error running command: Error: Prediction result array had 107 elements but labels list had 106 elements. They need to match.`

----------------------------------------------------------------------------------------------------

After the error above I deleted the test-ai-classifier and reinstalled it. Once reinstalled I pasted in the files from `web_model`. The shard file was a duplicate title so it asked me to replace and I did. The rest of the files pasted in no problem. 

My folder structure looks like this: 
![screen shot 2018-11-06 at 1 46 32 pm](https://user-images.githubusercontent.com/36003722/48086259-65a8ba00-e1ca-11e8-94d0-e35c79c12459.jpg)

Now I am getting: 

`driver.find_element(:custom => "ai:paper airplane")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from NoSuchElementError: An element could not be located on the page using the given search parameters.`

I can't tell if this is progress or not. 

I have a feeling its not correct but the pre-packaged finds are still working. 

`driver.find_element(:custom => "ai:mail")
=> #<Selenium::WebDriver::Element:0x..fd9bd9f88f08d316 id="A0000000-0000-0000-0614-000000000000">`

So while it's not finding the new elements that I was hoping I trained it for it is still working with the default data. 

--------------------------------------------------------------------------------------------------

New information! I just started playing around with the sample_run folder to see if I had trained the classifier on paper airplanes at all. Turns out paper airplanes are actually held in the "send" training images folder. So maybe this explains my issues?

**Comment by cnavrides** [comment] 2018-11-06 19:19
Oh whoops. Will figure out a better update strategy, but try modify [appium-classifier-plugin/lib/label.js](https://github.com/testdotai/appium-classifier-plugin/blob/master/lib/labels.js) to include paper airplane.

**Comment by ericsavoiewaltz** [comment] 2018-11-06 19:20
There seems to be a bug in the appium plugin as well https://github.com/testdotai/appium-classifier-plugin/issues/9

**Comment by ericsavoiewaltz** [comment] 2018-11-06 19:35
Working on the fix you suggested - just getting some of that boring regular work out of the way.

**Comment by cnavrides** [comment] 2018-11-06 19:58
> Does the retraining script train the sample_run run_model.py script as well?
No it doesn't. The `run_model.py` is just a sample script so you can view your model and the results without needing to convert and put them into appium first.

**Comment by ericsavoiewaltz** [comment] 2018-11-06 20:04
Okay so I tried updating appium-classifier-plugin/lib/label.js with the new label "paper airplane" and I got the same error. 

`An unknown server-side error occurred while processing the command. Original error: Prediction result array had 107 elements but labels list had 106 elements. They need to match. (Selenium::WebDriver::Error::UnknownError)
      UnknownError: An unknown server-side error occurred while processing the command. Original error: Prediction result array had 107 elements but labels list had 106 elements. They need to match.
          at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
          at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:450:37
          at Generator.next (<anonymous>)
          at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
          at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)`

**Comment by cnavrides** [comment] 2018-11-06 20:42
@ericsavoiewaltz - Are you sure you updated the right labels.json? It should be the `appium-classifier-plugin` folder under the `appium/node_modules`. 

The error is stating that there are 106 labels in labels.json but the model has 107 possible labels in the [classifier.js of appium-classifier-plugin](https://github.com/testdotai/appium-classifier-plugin/blob/master/lib/classifier.js#L68)

For clarity I will close this out here as the model appears to be built and converted properly with the labels,  and it appears the issue is in the classifier plugin. If the problem persists please open an issue on the appium-classifier-plugin project

**Closed by cnavrides** 2018-11-06 20:42 UTC

**Comment by ericsavoiewaltz** [comment] 2018-11-06 20:49
@cnavrides I'm confused. I don't have a folder under appium/node_modules called "appium-classifier-plugin" I have "test-ai-classifier". That is the folder that I updated the labels.js file in and where I pasted the model folder from the retrain script.

**Comment by cnavrides** [comment] 2018-11-06 20:53
Sorry. Got the github project name (appium-classifier-plugin) and npm name (test-ai-classifier) confused. It should be the `label.js` file under the `test-ai-classifier` folder.

**Comment by ericsavoiewaltz** [comment] 2018-11-06 20:55
Okay I've tried the labels.js file in that folder twice now. I'm not sure what I could be doing wrong. I'm quite sure I've done it correctly as far as inserting a new row into an array object goes.

**Comment by pramodKarande** [comment] 2019-04-12 09:24
@ericsavoiewaltz 
try updating label.js file located at /usr/local/lib/node_modules/appium/node_modules/test-ai-classifier/build/lib this location.
it worked for me.

**Comment by pramodKarande** [comment] 2019-04-12 09:27
@cnavrides 
do we need to keep images in specific resolution and format like .png/.jpg??

**Comment by vallme2003** [comment] 2020-09-13 07:11
Facing the same issue as @ericsavoiewaltz . Are there any updates to this?
